# Generated by Django 2.2.6 on 2020-12-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_post_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_like',
        ),
    ]
